name: end to end tests

on:
  repository_dispatch:
    types:
      - 'vercel.deployment.ready'
jobs:
  run-e2es:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}
      - name: Install dependencies
        run: npm install && npx cypress install --with-deps
      - name: Run tests
        run: npx cypress test
        env:
          NEXT_PUBLIC_BASE_URL: ${{ github.event.client_payload.url }}
